<?php
declare(strict_types=1);

/**
 * SOMBA - Client API Maketou
  *
   * API officielle :
    * https://api.maketou.net
     *
      * Création :
       * POST /api/v1/stores/cart/checkout
        *
         * Vérification :
          * GET /api/v1/stores/cart/{cartId}
           */

           require_once __DIR__ . '/../config/bootstrap.php';

           function maketouRequest(
               string $method,
                   string $path,
                       ?array $body = null
                       ): array {
                           $apiKey = (string) config('maketou.api_key', '');

                               if ($apiKey === '') {
                                       throw new RuntimeException('Maketou API key missing');
                                           }

                                               $url = 'https://api.maketou.net' . $path;

                                                   $ch = curl_init($url);

                                                       if ($ch === false) {
                                                               throw new RuntimeException('Unable to initialize cURL');
                                                                   }

                                                                       $headers = [
                                                                               'Authorization: Bearer ' . $apiKey,
                                                                                       'Accept: application/json',
                                                                                               'Content-Type: application/json',
                                                                                                   ];

                                                                                                       curl_setopt_array($ch, [
                                                                                                               CURLOPT_RETURNTRANSFER => true,
                                                                                                                       CURLOPT_CUSTOMREQUEST => strtoupper($method),
                                                                                                                               CURLOPT_HTTPHEADER => $headers,
                                                                                                                                       CURLOPT_TIMEOUT => 30,
                                                                                                                                               CURLOPT_CONNECTTIMEOUT => 10,
                                                                                                                                                   ]);

                                                                                                                                                       if ($body !== null) {
                                                                                                                                                               $json = json_encode(
                                                                                                                                                                           $body,
                                                                                                                                                                                       JSON_UNESCAPED_UNICODE |
                                                                                                                                                                                                   JSON_UNESCAPED_SLASHES |
                                                                                                                                                                                                               JSON_THROW_ON_ERROR
                                                                                                                                                                                                                       );

                                                                                                                                                                                                                               curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                       $response = curl_exec($ch);

                                                                                                                                                                                                                                           if ($response === false) {
                                                                                                                                                                                                                                                   $error = curl_error($ch);
                                                                                                                                                                                                                                                           curl_close($ch);

                                                                                                                                                                                                                                                                   throw new RuntimeException(
                                                                                                                                                                                                                                                                               'Maketou connection error: ' . $error
                                                                                                                                                                                                                                                                                       );
                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                               $httpCode = (int) curl_getinfo(
                                                                                                                                                                                                                                                                                                       $ch,
                                                                                                                                                                                                                                                                                                               CURLINFO_HTTP_CODE
                                                                                                                                                                                                                                                                                                                   );

                                                                                                                                                                                                                                                                                                                       curl_close($ch);

                                                                                                                                                                                                                                                                                                                           $data = json_decode($response, true);

                                                                                                                                                                                                                                                                                                                               if (!is_array($data)) {
                                                                                                                                                                                                                                                                                                                                       throw new RuntimeException(
                                                                                                                                                                                                                                                                                                                                                   'Invalid Maketou response'
                                                                                                                                                                                                                                                                                                                                                           );
                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                   if ($httpCode < 200 || $httpCode >= 300) {
                                                                                                                                                                                                                                                                                                                                                                           $message =
                                                                                                                                                                                                                                                                                                                                                                                       $data['message']
                                                                                                                                                                                                                                                                                                                                                                                                   ?? 'Maketou API error';

                                                                                                                                                                                                                                                                                                                                                                                                           throw new RuntimeException(
                                                                                                                                                                                                                                                                                                                                                                                                                       'Maketou HTTP ' .
                                                                                                                                                                                                                                                                                                                                                                                                                                   $httpCode .
                                                                                                                                                                                                                                                                                                                                                                                                                                               ': ' .
                                                                                                                                                                                                                                                                                                                                                                                                                                                           $message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return $data;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                           /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * Crée un panier Maketou.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             function maketouCreateCart(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 string $productDocumentId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     string $email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         string $firstName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             string $lastName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ?string $phone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     string $redirectUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         array $meta = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ): array {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $payload = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'productDocumentId' => $productDocumentId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'email' => $email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'firstName' => $firstName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'lastName' => $lastName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'redirectURL' => $redirectUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if ($phone !== null && $phone !== '') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $payload['phone'] = $phone;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if ($meta !== []) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $payload['meta'] = $meta;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return maketouRequest(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             '/api/v1/stores/cart/checkout',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     $payload
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Récupère un panier Maketou.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           function maketouGetCart(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               string $cartId
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ): array {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (!preg_match(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '/^[a-f0-9-]{36}$/i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   $cartId
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       )) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               throw new InvalidArgumentException(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'Invalid Maketou cart ID'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return maketouRequest(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'GET',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '/api/v1/stores/cart/' .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   rawurlencode($cartId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }