<?php
declare(strict_types=1);

/**
 * SOMBA — Topup.dev
  *
   * IMPORTANT :
    * Ne pas inventer l'URL d'API.
     *
      * Ce fichier attend l'endpoint officiel Topup.dev
       * et le format exact de création de commande.
        */

        require_once __DIR__ . '/../config/bootstrap.php';


        function topupRequest(
            string $method,
                string $url,
                    ?array $payload = null
                    ): array {

                        $apiKey =
                                (string) config(
                                            'topup.api_key',
                                                        ''
                                                                );

                                                                    if ($apiKey === '') {
                                                                            throw new RuntimeException(
                                                                                        'Topup.dev API key missing'
                                                                                                );
                                                                                                    }

                                                                                                        if ($url === '') {
                                                                                                                throw new RuntimeException(
                                                                                                                            'Topup.dev API URL missing'
                                                                                                                                    );
                                                                                                                                        }

                                                                                                                                            $ch = curl_init($url);

                                                                                                                                                if ($ch === false) {
                                                                                                                                                        throw new RuntimeException(
                                                                                                                                                                    'Unable to initialize cURL'
                                                                                                                                                                            );
                                                                                                                                                                                }

                                                                                                                                                                                    $headers = [
                                                                                                                                                                                            'Authorization: Bearer ' . $apiKey,
                                                                                                                                                                                                    'Accept: application/json',
                                                                                                                                                                                                            'Content-Type: application/json',
                                                                                                                                                                                                                ];

                                                                                                                                                                                                                    curl_setopt_array($ch, [
                                                                                                                                                                                                                            CURLOPT_RETURNTRANSFER => true,
                                                                                                                                                                                                                                    CURLOPT_CUSTOMREQUEST => strtoupper($method),
                                                                                                                                                                                                                                            CURLOPT_HTTPHEADER => $headers,
                                                                                                                                                                                                                                                    CURLOPT_TIMEOUT => 60,
                                                                                                                                                                                                                                                            CURLOPT_CONNECTTIMEOUT => 10,
                                                                                                                                                                                                                                                                ]);

                                                                                                                                                                                                                                                                    if ($payload !== null) {

                                                                                                                                                                                                                                                                            $json = json_encode(
                                                                                                                                                                                                                                                                                        $payload,
                                                                                                                                                                                                                                                                                                    JSON_UNESCAPED_UNICODE |
                                                                                                                                                                                                                                                                                                                JSON_UNESCAPED_SLASHES |
                                                                                                                                                                                                                                                                                                                            JSON_THROW_ON_ERROR
                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                            curl_setopt(
                                                                                                                                                                                                                                                                                                                                                        $ch,
                                                                                                                                                                                                                                                                                                                                                                    CURLOPT_POSTFIELDS,
                                                                                                                                                                                                                                                                                                                                                                                $json
                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                $response = curl_exec($ch);

                                                                                                                                                                                                                                                                                                                                                                                                    if ($response === false) {

                                                                                                                                                                                                                                                                                                                                                                                                            $error = curl_error($ch);

                                                                                                                                                                                                                                                                                                                                                                                                                    curl_close($ch);

                                                                                                                                                                                                                                                                                                                                                                                                                            throw new RuntimeException(
                                                                                                                                                                                                                                                                                                                                                                                                                                        'Topup.dev connection error: ' .
                                                                                                                                                                                                                                                                                                                                                                                                                                                    $error
                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $httpCode =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            (int) curl_getinfo(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $ch,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CURLINFO_HTTP_CODE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                curl_close($ch);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $data = json_decode(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $response,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!is_array($data)) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    throw new RuntimeException(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Invalid Topup.dev response'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $httpCode < 200 ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $httpCode >= 300
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            throw new RuntimeException(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'Topup.dev HTTP ' .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $httpCode .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ': ' .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ($data['message'] ?? 'Unknown error')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return $data;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * À appeler uniquement APRÈS confirmation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * du paiement Maketou.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * Cette fonction reste volontairement bloquée
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * tant que l'endpoint officiel Topup.dev n'est
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * pas configuré.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   function topupDeliver(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       string $sku,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           string $playerId
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ): array {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $endpoint =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       (string) config(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'topup.endpoint',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if ($endpoint === '') {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   throw new RuntimeException(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               'Topup.dev endpoint not configured. ' .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'Configure the official endpoint before enabling delivery.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           /*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * Le payload exact doit correspondre
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * à la documentation Topup.dev.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * Exemple de structure interne SOMBA :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $payload = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'sku' => $sku,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'player_id' => $playerId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return topupRequest(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $endpoint,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $payload
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }